name: Contracts
on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

jobs:
  test:
    name: "Contracts: Unit Tests"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./contracts
    env:
      REPORT_GAS: true
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
